# Generated by Django 5.2.11 on 2026-02-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
